name: CI

on:
    push:
        branches: ["main"]
    pull_request:
        types: [opened, synchronize]

jobs:
    build:
        name: Check for Successful Build
        timeout-minutes: 15
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Setup
              uses: ./.github/actions/setup

            - name: Build
              run: pnpm build

    eslint:
        name: Check Formatting
        timeout-minutes: 15
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Setup
              uses: ./.github/actions/setup

            - name: Run ESLint
              uses: sibiraj-s/action-eslint@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  eslint-args: "--ignore-path=.gitignore --quiet"
                  extensions: "js,jsx,ts,tsx"
                  annotations: true
